# -*- coding: utf-8 -*-
"""MediaAluno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfhCB4ng7ja5mQj0e7AuupJMxoIcpkPW
"""

aluno = input('digite o nome do aluno: ')
n1 = float(input('digite a primeira nota: '))
n2 = float(input('digite a segunda nota: '))
n3 = float(input('digite a teceira nota: '))
media = (n1+n2+n3)/3
if media >= 7:
    situação = 'aprovado'
elif media >= 5:
    situção = 'ficou de recuperação'
else:
    situação = 'foi reprovado'
print(f'o aluno {aluno} {situação} com media {media:.2f}')